# Generated by Django 5.0.6 on 2026-08-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_access_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether Two-Factor Authentication is activated for this account.', verbose_name='2FA Activated'),
        ),
    ]
