# Generated by Django 5.0.6 on 2026-06-16 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0002_compliancerequirement_subcontractorcompliance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False, verbose_name='S/N')),
                ('mda', models.CharField(help_text='Ministry, Department, or Agency', max_length=255, verbose_name='MDA')),
                ('project_code', models.CharField(max_length=100, unique=True, verbose_name='Project Code')),
                ('project_name', models.CharField(max_length=512, verbose_name='Project Name')),
                ('lot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot')),
                ('project_type', models.CharField(choices=[('CONSTRUCTION', 'Construction / Civil Works'), ('SUPPLY_TRAINING', 'Supply and Training Project')], default='CONSTRUCTION', max_length=20, verbose_name='Type')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('plain_boq', models.FileField(blank=True, null=True, upload_to='projects/boq/plain/', verbose_name='Plain BOQ')),
                ('drawing_design', models.FileField(blank=True, null=True, upload_to='projects/drawings/', verbose_name='Drawing/Design')),
                ('award_letter_and_boq', models.FileField(blank=True, null=True, upload_to='projects/boq/awarded/', verbose_name='Award Letter and BOQ')),
                ('final_companies', models.TextField(blank=True, null=True, verbose_name='Final Companies')),
                ('back_up_companies', models.TextField(blank=True, null=True, verbose_name='Back up Companies')),
                ('updated_recommended_companies', models.TextField(blank=True, null=True, verbose_name='Updated Recommended Companies')),
                ('technical_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical')),
                ('financial_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Financials')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Budget Amount')),
                ('actual_contract_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Actual Contract Amount')),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Admin Fee')),
                ('in_house_benchmark', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='In-House Benchmark (Direct Labour)')),
                ('cost_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., 65.50 for 65.5%', max_digits=5, verbose_name='Cost Percentage')),
                ('mobilization_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Mobilization Received')),
                ('batch_no_mobilization', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No. Mobilization')),
                ('batch_no_final_payment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch No. Final Payment')),
                ('final_payment_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Final Payment Received')),
                ('current_phase', models.CharField(choices=[('PRE_AWARD', 'Bidding / Pre-Award Phase'), ('POST_AWARD', 'Execution / Post-Award Phase'), ('PAYMENT_PROCESSING', 'Application & Payment Processing'), ('COMPLETED', 'Project Fully Closed / Paid')], default='PRE_AWARD', max_length=20)),
                ('level_of_completion_percentage', models.PositiveIntegerField(default=0, verbose_name='Level of Completion %')),
                ('project_status', models.CharField(default='Initiated', max_length=100, verbose_name='Project Status')),
                ('payment_status', models.CharField(default='Pending', max_length=100, verbose_name='Payment Status')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff Assigned')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_contractor_drawing_design', models.FileField(blank=True, null=True, upload_to='subcontractors/drawings/', verbose_name='Sub-Contractor Drawing/Design')),
                ('supplier_contractor_price_boq', models.FileField(blank=True, null=True, upload_to='subcontractors/boq/', verbose_name='Supplier/Contractor Price 1/BOQ')),
                ('sub_contractor_cost_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Sub-Contractor Cost Percentage')),
                ('amount_agreed_with_supplier_contractor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount Agreed with Supplier/Contractor')),
                ('advance_received_by_supplier_contractor', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Advance Received by Supplier/Contractor')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.subcontractor', verbose_name='Sub-Contractor')),
            ],
            options={
                'verbose_name': 'Project Subcontractor Allocation',
                'verbose_name_plural': 'Project Subcontractor Allocations',
                'unique_together': {('project', 'subcontractor')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='subcontractors',
            field=models.ManyToManyField(related_name='assigned_projects', through='projects.ProjectAllocation', to='contractors.subcontractor'),
        ),
        migrations.CreateModel(
            name='ProjectLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(help_text="e.g., 'Bi-weekly Purchase of Federal Tender Journal', 'Submission of Batch Numbers to AGF'", max_length=255)),
                ('sequence_order', models.PositiveIntegerField(help_text='Determines the workflow pipeline order sequence')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes_or_updates', models.TextField(blank=True, help_text='Use this to log internal processing stage and file movement details', null=True)),
                ('incurred_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Capture processing costs, profile updates, journal purchase costs, or follow-up expenses here.', max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_stages', to='projects.project')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('project', 'stage_name')},
            },
        ),
    ]
