# Generated by Django 5.0.6 on 2026-06-25 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnplannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description of what the expense was for.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the unplanned expense.', max_digits=14)),
                ('date_incurred', models.DateField(help_text='Date the expense was incurred.')),
                ('notes', models.TextField(blank=True, help_text='Optional additional notes or justification for this expense.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unplanned_expenses', to='projects.project')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unplanned Expense',
                'verbose_name_plural': 'Unplanned Expenses',
                'ordering': ['-date_incurred'],
            },
        ),
    ]
