# Generated by Django 5.0.6 on 2026-06-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_unplannedexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unplannedexpense',
            name='notes',
        ),
    ]
