# Generated by Django 5.0.6 on 2026-07-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_unplannedexpense_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fee Type Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Project Category',
                'verbose_name_plural': 'Project Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='admin_fee',
        ),
        migrations.AddField(
            model_name='project',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='projects.project', verbose_name='Linked Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Old'),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_phase',
            field=models.CharField(choices=[('PRE_AWARD', 'Pre-Award Phase'), ('POST_AWARD', 'Post-Award Phase'), ('EXECUTION', 'Execution Phase')], default='PRE_AWARD', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='ProjectFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.feetype', verbose_name='Fee Type')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Fee',
                'verbose_name_plural': 'Project Fees',
                'unique_together': {('project', 'fee_type')},
            },
        ),
    ]
