# Generated by Django 5.0.6 on 2026-07-02 15:28

from django.db import migrations

def migrate_categories_and_seed_defaults(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ProjectCategory = apps.get_model('projects', 'ProjectCategory')
    FeeType = apps.get_model('projects', 'FeeType')
    
    # 1. Seed categories
    categories = ["POWER", "Construction", "Supply", "Empower"]
    cat_objs = {}
    for cat in categories:
        obj, _ = ProjectCategory.objects.get_or_create(name=cat)
        cat_objs[cat.lower()] = obj
        
    # 2. Seed fee types
    fee_types = ["Admin Fee", "Tender Fee", "VAT", "Withholding Tax", "Contingency"]
    for fee in fee_types:
        FeeType.objects.get_or_create(name=fee)
        
    # 3. Migrate category CharField values to ForeignKey category_fk
    for project in Project.objects.all():
        if project.category:
            val = project.category.strip()
            if val:
                cat_lower = val.lower()
                if cat_lower in cat_objs:
                    project.category_fk = cat_objs[cat_lower]
                else:
                    obj, _ = ProjectCategory.objects.get_or_create(name=val)
                    cat_objs[cat_lower] = obj
                    project.category_fk = obj
                project.save()

def reverse_migrate_categories(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        if project.category_fk:
            project.category = project.category_fk.name
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_feetype_projectcategory_remove_project_admin_fee_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_categories_and_seed_defaults, reverse_migrate_categories),
    ]
