# Generated by Django 5.0.6 on 2026-07-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_migrate_category_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category_fk',
            new_name='category',
        ),
    ]
