# Generated by Django 5.0.6 on 2026-07-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_category_fk_alter_project_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='level_of_completion_percentage',
        ),
        migrations.AddField(
            model_name='project',
            name='execution_level_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Execution Level %'),
        ),
    ]
