# Generated by Django 5.0.6 on 2026-07-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_level_of_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='execution_mode',
            field=models.CharField(choices=[('SELF_EXECUTED', 'Self-Executed (Direct Labor)'), ('SUBCONTRACTED', 'Given to Sub-Contractor')], default='SELF_EXECUTED', max_length=20, verbose_name='Execution Mode'),
        ),
        migrations.CreateModel(
            name='ProjectMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the monitoring period/visit')),
                ('end_date', models.DateField(blank=True, help_text='End date if the monitoring spans multiple days', null=True)),
                ('description', models.TextField(help_text='Detailed description of current progress, site conditions, or issues.')),
                ('reported_execution_percentage', models.PositiveIntegerField(help_text="The engineer's assessment of the overall physical progress (0 to 100)")),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_logs', to='projects.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Monitoring Log',
                'verbose_name_plural': 'Project Monitoring Logs',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMonitoringImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/monitoring_logs/')),
                ('caption', models.CharField(blank=True, help_text="Optional description of what this image shows (e.g., 'Foundation pouring progress')", max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('monitoring_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectmonitoringlog')),
            ],
            options={
                'verbose_name': 'Project Monitoring Image',
                'verbose_name_plural': 'Project Monitoring Images',
            },
        ),
    ]
