# Generated by Django 5.0.6 on 2026-07-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_execution_mode_projectmonitoringlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorPaymentTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount Paid')),
                ('date_paid', models.DateField(verbose_name='Date Paid')),
                ('payment_reference', models.CharField(blank=True, help_text='e.g., Bank transfer Ref, Receipt #', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional details or remarks.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tranches', to='projects.projectallocation')),
            ],
            options={
                'verbose_name': 'Subcontractor Payment Tranche',
                'verbose_name_plural': 'Subcontractor Payment Tranches',
                'ordering': ['-date_paid', '-created_at'],
            },
        ),
    ]
