# Generated by Django 5.0.6 on 2026-07-10 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_subcontractorpaymenttranche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='linked_project',
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_parts', to='projects.project', verbose_name='Parent Project (for Split Parts)'),
        ),
        migrations.AddField(
            model_name='project',
            name='part_name',
            field=models.CharField(blank=True, help_text='e.g. Phase 1, Phase 2, Part A', max_length=100, null=True, verbose_name='Part Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='part_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='e.g. 60.00 for 60%', max_digits=5, verbose_name='Part Percentage'),
        ),
        migrations.AddField(
            model_name='project',
            name='rolled_over_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_over_to', to='projects.project', verbose_name='Rolled Over From'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(max_length=100, verbose_name='Project Code'),
        ),
    ]
