# Generated by Django 5.0.6 on 2026-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_linked_project_project_parent_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='award_letter_and_boq',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Award Letter & BOQ (SharePoint Link)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='drawing_design',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Drawing/Design (SharePoint Link)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plain_boq',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Plain BOQ (SharePoint Link)'),
        ),
    ]
