# Generated by Django 5.0.6 on 2026-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_award_letter_and_boq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfee',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Date Paid'),
        ),
        migrations.AddField(
            model_name='projectfee',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='e.g., Bank transfer ref, receipt #', max_length=255, null=True, verbose_name='Payment Reference'),
        ),
        migrations.AddField(
            model_name='projectfee',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / Estimated'), ('PAID', 'Paid / Disbursed')], default='PENDING', max_length=15, verbose_name='Status'),
        ),
    ]
