# Generated by Django 5.0.6 on 2026-08-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectfee_date_paid_projectfee_payment_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Project Created'), ('UPDATE', 'Project Details Updated'), ('FEE', 'Fee Schedule Updated'), ('STAGE', 'Lifecycle Stage Progressed'), ('EXPENSE', 'Unplanned Expense Logged'), ('SUBCONTRACTOR', 'Subcontractor Allocated'), ('TRANCHE', 'Payment Tranche Disbursed'), ('MONITORING', 'Site Monitoring Logged')], default='UPDATE', max_length=20)),
                ('title', models.CharField(help_text='Short headline summary of the change', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed summary of updates or observations', null=True)),
                ('changes_json', models.JSONField(blank=True, default=dict, help_text='Before & after field value diffs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Activity Log',
                'verbose_name_plural': 'Project Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
