# Generated by Django 5.0.6 on 2026-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_convert_mda_to_short_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priced_boq',
            field=models.FileField(blank=True, null=True, upload_to='projects/boq/priced/', verbose_name='Priced BOQ'),
        ),
    ]
