# Generated by Django 5.0.6 on 2026-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_priced_boq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='award_letter_and_boq',
            field=models.FileField(blank=True, null=True, upload_to='projects/boq/awarded/', verbose_name='Award Letter and BOQ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='drawing_design',
            field=models.FileField(blank=True, null=True, upload_to='projects/drawings/', verbose_name='Drawing/Design'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plain_boq',
            field=models.FileField(blank=True, null=True, upload_to='projects/boq/plain/', verbose_name='Plain BOQ'),
        ),
    ]
