# Generated by Django 5.0.6 on 2026-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_award_letter_and_boq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technical_status',
        ),
        migrations.AddField(
            model_name='project',
            name='financial_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Financial Submission Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Technical Submission Date'),
        ),
    ]
