# Generated by Django 5.0.6 on 2026-09-03 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_project_financial_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Project Created'), ('UPDATE', 'Project Details Updated'), ('FEE', 'Fee Schedule Updated'), ('STAGE', 'Lifecycle Stage Progressed'), ('EXPENSE', 'Unplanned Expense Logged'), ('SUBCONTRACTOR', 'Subcontractor Allocated'), ('TRANCHE', 'Payment Tranche Disbursed'), ('MONITORING', 'Site Monitoring Logged'), ('PHASE_COMMENT', 'Phase Comment Added')], default='UPDATE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectPhaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRE_AWARD', 'Pre-Award Phase'), ('POST_AWARD', 'Post-Award Phase'), ('EXECUTION', 'Execution Phase')], max_length=20, verbose_name='Phase')),
                ('comment', models.TextField(verbose_name='Comment / Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_comments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_comments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Phase Comment',
                'verbose_name_plural': 'Project Phase Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
