# Generated by Django 5.0.6 on 2026-06-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_record_project_alter_request_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='material',
            name='project',
        ),
        migrations.RemoveField(
            model_name='store',
            name='material',
        ),
        migrations.RemoveField(
            model_name='record',
            name='material',
        ),
        migrations.RemoveField(
            model_name='request',
            name='material',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='material',
        ),
        migrations.RemoveField(
            model_name='record',
            name='project',
        ),
        migrations.RemoveField(
            model_name='request',
            name='project',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='store',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='project',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
