# Generated by Django 5.0.6 on 2026-06-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_title', models.CharField(help_text='e.g., Foundation Pouring, Blockwork Level 1', max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justification_notes', models.TextField(help_text="Engineer's breakdown of what the money will execute.")),
                ('status', models.CharField(choices=[('PENDING', 'Pending Management Approval'), ('APPROVED', 'Approved & Funded'), ('REJECTED', 'Rejected / Clarification Needed')], default='PENDING', max_length=15)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_actioned', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='e.g., Cement, 16mm Rebar, Screeding Paint', max_length=150)),
                ('quantity_on_site', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit_of_measurement', models.CharField(help_text='e.g., Bags, Tons, Liters', max_length=50)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_inventory', to='projects.project')),
            ],
            options={
                'verbose_name': 'Site Store Inventory',
                'verbose_name_plural': 'Site Store Inventories',
                'unique_together': {('project', 'material_name')},
            },
        ),
        migrations.CreateModel(
            name='SiteUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_used', models.DateField()),
                ('activity_details', models.CharField(help_text='e.g., Casted pillar alignment 1-5', max_length=255)),
                ('site_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='logistic.sitestore')),
            ],
        ),
    ]
