# Generated by Django 5.0.6 on 2026-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonecashrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Management Approval'), ('APPROVED', 'Approved & Funded'), ('REJECTED', 'Rejected / Clarification Needed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
