# Generated by Django 5.0.6 on 2026-07-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_alter_milestonecashrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecashrequest',
            name='management_comment',
            field=models.TextField(blank=True, help_text='Reviewer comments or reasons for decision.', null=True),
        ),
    ]
