import os
import sys
import re
import datetime
from decimal import Decimal

sys.path.insert(0, os.getcwd())
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'material_logistics.settings')
import django
django.setup()

from django.db import transaction
from django.contrib.auth.models import User
from projects.models import Project, ProjectCategory, FeeType, ProjectFee, ProjectAllocation
from contractors.models import Subcontractor

RAW_DATA = """1	AJAOKUTA STEEL COMPANY LIMITED (ASCL)	ERGP10235818	SUPPLY AND INSTALLATION OF ALL IN ONE SOLAR STREET LIGHT ACROSS SOME SELECTED COMMUNITIES IN NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST SENATORIAL DISTRICT	POWER	2025 ASCL 1		70000000.00																										AICON SOLAR LIMITED					
2	BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) HQTRS	ERGP22236601	ROAD REHABILITATION OF SELECTED KAGARA COMMUNITY ROADS (ASPHALT) AND GWADA, NIGER STATE.			ONGOING	KAGARA, GWADA	CONSTRUCTION	2025 BCDA 2		210000000.00																										M&W RESOURCES LIMITED					
3	BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) HQTRS	ERGP22236604	CONSTRUCTION OF LECTURE THEATRE AND SCIENCE AUDITORIUM AND LANDSCAPING AT INSTITUTE OF CONTINUED EDUCATION AND E-LEARNING PAIKO.			ONGOING	PAIKO	CONSTRUCTION	2025 BCDA 1		280000000.00																										CHELIXIR NIG LTD- (OFFICE)					
4	BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) HQTRS	ERGP30236204	REHABILITATION AND THE FURNISHING OF THE OFFICIAL PALACE OF THE DISTRICT HEAD OF PAIKO			ONGOING	PAIKO	CONSTRUCTION	2025 BCDA 5		350000000.00																										GRAND LEGEND PLUS LTD - (OFFICE)					
5	BORDER COMMUNITIES DEVELOPMENT AGENCY (BCDA) HQTRS	ERGP30236206	CONSTRUCTION OF 4NOS 50 BED MODERN DIAGNOSTIC MEDICAL CENTER IN RAFI (KAGARA), /MAKERA MINNA,/ IJAH GWARI AND BOSSO (MAIKUNKELE)			ONGOING	RAFI (KAGARA), MAKERA MINNA, IJAH GWARI, BOSSO (MAIKUNKELE) 	CONSTRUCTION	2025 BCDA 4		980000000.00																										"1. M&W RESOURCES LIMITED - (YARIMA)                        
2. OCEANBED CONSULTANT SERVICES LTD -(ISAAC)         
3. AICON CIVIL ENGINEERING LTD - (YARIMA)                    
"					
6	FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER (FCCO)	ERGP30236851	ESTABLISHMENT OF PLASTIC RECYCLING AND PROCESSING CENTERS AND PROVISION OF 100 SHREDDING AND PLASTIC MACHINERY MANUFACTURER FOR WASTE PP PE FILM PLASTIC BAGS HIGH EFFICIENCY CRUSHING MACHINE S/KAHUTA INDUSTRIAL LAYOUT			ONGOING	S/KAHUTA 	CONSTRUCTION/SUPPLY	2025 FCC OJI RIVER  1		350000000.00																										M&W RESOURCES LTD - (YARIMA)					
7	FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER (FCCO)	ERGP30236856	TRAINING OF YOUTH IN AGRICULTURE TECHNOLOGY, VACATIONAL SKILLS ACQUISITION, POST HARVEST HANDLING & PRECISION FARMING SKILLS IN NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST SENATORIAL DISTRICT	TRAINING	2025 FCC OJI RIVER  2		210000000.00																										SYNERSIS LINEAR INT'I LIMITED					
8	FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER (FCCO)	ERGP20272548	CONSTRUCTION OF MODERN MINI- MARKETS AND PROVISION OF FACILITIES IN SELECTED LOCATIONS IN NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST SENATORIAL DISTRICT	CONSTRUCTION	2025 FCC OJI RIVER  6		350000000.00																										M&W RESOURCES LTD - (YARIMA)					
9	FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER (FCCO)	ERGP20272549	REHABILITATION AND REMODELLING OF CLASSROOMS AND SUPPLY OF FURNITURE IN SELECTED SCHOOLS ACROSS NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST SENATORIAL DISTRICT	CONSTRUCTION	2025 FCC OJI RIVER  7		210000000.00																										GRANDLEGEND PLUS LIMITED (OFFICE)					
10	FEDERAL CO-OPERATIVE COLLEGE- OJI RIVER (FCCO)	ERGP20272550	REHABILITATION OF WATER WORKS IN ILEMONA, OYUN LGA OF KWARA STATE			ONGOING	ILEMONA OYUN LGA KWARA STATE	CONSTRUCTION	2025 FCC OJI RIVER  8		350000000.00																										BLUE ELEMENT LIMITED (MUHAMMED SK)  					
11	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245372	RENOVATION AND UPGRADE OF ABUBAKAR DADA SEC. SCHOOL TO A PILOT TECHNOLOGY EDUCATION SCHOOL WITH CLASSROOMS, ADMINISTRATIVE OFFICE BUILDING AND HOSTELS. (2) UPGRADE AND RENOVATION OF GOVT SEC. SCH PAGO TO PILOT TECHNOLOGY EDUCATION SCHOOL CLASSROOMS, ADMINISTRATIVE OFFICE BUILDING AND PARIMETER FENCING IN PAGO- NORTH CENTRAL ZONE.			ONGOING		CONSTRUCTION	1-3 FCHTDK 2025		840000000.00																										1. GRANDLEGEND PLUS LIMITED- (OFFICE),                                                                 2. MJW PARTNERS & SERVICES LIMITED - (YARIMA)                                                                             3. SELSA LOGISTICS SERVICES LIMITED - (OFFICE)					
12	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245376	PROVISION OF 15HP HAND OPERATED FARM TRACTOR WITH PLOUGH 18HP MINI TRACTOR FOR FARMERS IN NIGER EAST SENATORIAL DISTRICT.			ONGOING		SUPPLY	4-7 FCHTDK 2025		280000000.00																										1. SANEX GLOBAL LOGISTICS LIMITED - (OFFICE)                                                        2. SELSA INVESTMENT LIMITED - (OFFICE)                                                          3. ZEDMAN GLOBAL LIMITED - (OFFICE)    					
13	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245379	CONSTRUCTION OF PROMETRIC CENTRE IN A SELECTED LOCATION IN T/WADA MX			ONGOING		CONSTRUCTION	23-25 FCHTDK 2025		1050000000.00																										1. BAKUS MULTI-LINKS SERVICES LIMITED                                                               2. AICON CIVIL ENGINEERING LIMITED					
14	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245409	CONSTRUCTION OF MINI STADIUMS WITH FLOOD LIGHTINING SYSTEM IN PAIKO (PAIKORO LGA) AND KUTA (SHIRORO LGA) AND CONSTRUCTION OF MINI STADIUMS IN GAWU BABANGIDA (GURARA LGA) AND SABON BWARI (TAFA LGA)			ONGOING		CONSTRUCTION	8-11 FCHTDK 2025		1120000000.00																										M&W RESOURCES LIMITED -(YARIMA)					
15	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245410	PROVISION OF UTILITY 4WD VEHICLES FOR SECURITY AGENCIES TO FACILITATE THE FIGHT AGAINST BANDITRY IN SHIRORO, RAFI, PAIKORO AND MUNYA IN NIGER STATE			ONGOING		SUPPLY	12-17 FCHTDK 2025		420000000.00																										"

1. NAS CAPITAL LIMITED - (YARIMA)
2. FONSOT GLOBAL SERVICES LIMITED -  (MUHAMMED SK)                                                          3. HASHTAG TECHNOLOGY LIMITED -(ISAAC)                                                                     4. SABIRUN NIGERIA LTD - (MUHAMMED SK)                                                                           5. LAITH COMPANY LTD - (YARIMA)"					
16	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245412	REHABILITATION OF TUNGAN MALLAM - NIKUCHI ROAD (SUB-SEC II) AND (2) REHABILITATION OF OLD MARKET ROAD PAIKO. NIGER STATE			ONGOING		CONSTRUCTION	18-20 FCHTDK 2025		1050000000.00																										1. PRICE ENERGY LIMITED - (ISAAC)                                                            2. SYNERSIS LINEAR INTERNATIONAL LIMITED - (YARIMA)                                                  3.  IRON FLUX LIMITED - (MUHAMMED SK)                                                               					
17	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP1245413	REHABILITATION OF KWAKUTI - KAFIN KORO - ISHAU ROAD NIGER STATE (SECTION B)			ONGOING		CONSTRUCTION	22 FCHTDK 2025		700000000.00																										EMPTECH TECHNOLOGIES NIGERIA LIMITED - (OFFICE)					
18	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP20273417	SUPPLY OF AGRICULTURAL IMPLEMENTS, PESTICIDES AND FERTILISERS FOR NEXT FARMING SEASON IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY	26 FCHTDK 2025		350000000.00																										OCEANIC WORLD SYSTEMS SERVICES LIMITED					
19	FEDERAL COLLEGE OF HORTICULTURE, DADIN-KOWA, GOMBE (FCHTDK)	ERGP20273418	RENOVATION AND EQUIPPING OF SELECTED SCIENCE LABORATORIES ACROSS NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION	27 FCHTDK 2025		210000000.00																										NAS CAPITAL LIMITED (YARIMA)					
20	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP12211920	REHABILITATION OF KWAKUTI  - KAFIN KORO - ISHAU ROAD AND TUGAN MALLAM- NIKUCHI ROAD IN PAIKORO NIGER STATE			ONGOING	KAFIN KORO- ISHAU ROAD	CONSTRUCTION	2025 FERMA 1, 2		87500000.00																										MUBA MULTI CONCEPT SERVICES LIMITED                                                                                					
21	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP12234475	REHABILITATION OF TUNGAN MALLAM - NIKUCHI ROAD NIGER STATE			ONGOING	PAIKO	CONSTRUCTION	2025 FERMA 1		210000000.00																										HERITAGEPLUS MULTI CONCEPT SERVICES LIMITED					
22	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP12234476	REHABILITATION OF KWAKUTI - KAFIN KORO - ISHAU ROAD NIGER STATE			ONGOING	PAIKO	CONSTRUCTION	2025 FERMA 2		210000000.00																										GRANDLEGEND PLUS LIMITED					
23	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP12234484	CONSTRUCTION OF GWAZUNU - GAURAKA ROAD (B - DIVISION) SULEJA NIGER STATE			ONGOING	GWAZUNU - GAURAKA B DIVISION SULEJA	CONSTRUCTION	2025 FERMA 3		420000000.00																										IBG CONSTRUCTION AND ASSOC SERVICES LTD (YARIMA)					
24	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP12234485	CONSTRUCTION OF SELECTED ROADS AT THE MINNA AIRPORT MAIKUNKELE FARM CENTERS AND AGRO PROCESSING ZONE.			ONGOING	MINNA AIRPORT	CONSTRUCTION	2025 FERMA 4		280000000.00																										MUBA MULTI CONCEPT SERVICES LTD(OFFICE)					
25	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP20276863	RECONSTRUCTION OF GBASEGO ROAD AND SELECTED RURAL ROADS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			1000000000.00																										IBG CONSTRUCTION AND ASSOC SERVICES LIMITED					
26	FEDERAL ROAD MAINTENANCE AGENCY (FERMA)	ERGP20276864	DESIGN AND CONSTRUCTION OF KWAKUTI - KAFIN KORO - ISHAU - AMALE - KATARI ROAD (SECTION 1) IN NIGER EAST SENATORIAL DISTRICT, NIGER STATE			ONGOING	KWAKUTI - KAFIN KORO - ISHAU	CONSTRUCTION			2500000000.00																										M&W RESOURCES LIMITED					
27	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP12244066	CONSTRUCTION OF (1) MASSALLACIN IDI ROAD, (2) ALI AKOI ALLAH ROAD, (3) SAIFU ROAD (4) UNGUWAN GABAS ROAD, (1) KOROPA ROAD, (2) TSOHON KASUWA ROAD (3) P&P ROAD (4) MILLIONAIRE QUARTERS ROAD			ONGOING	MASSALLACIN IDI ROAD, P&P ROAD, AND MILLIONAIRE QUARTERS ROAD	CONSTRUCTION	2025 FMHUD 1		1120000000.00																										OCEANBED CONSULTANT SERVICES LIMITED					
28	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP1244077	CONSTRUCTION OF RURAL MARKETS IN SELECTED LOCATIONS IN NIGER EAST SENATORIAL DISTRICT			ONGOING	 NIGER EAST SENATORIAL DISTRICT	CONSTRUCTION	2025 FMHUD 4		182000000.00																										SANEX GLOBAL LIMITED (OFFICE)					
29	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP23244068	CONSTRUCTION OF PERIMETER AND COMMONROOM AT THE INSTITUTE OF CONTINUED EDUCATION AND E-LEARNING PAIKO			ONGOING	PAIKO	CONSTRUCTION	2025 FMHUD 8		140000000.00																										BLUE ELEMENT LIMITED (MUHAMMED SK)					
30	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP23244081	PROVISION OF BUSES FOR SCHOOL SHUTTLE, COMMUTTER SERVICES AND SECURITY PATROL IN ZONE B MX AND BOSSO			ONGOING	 ZONE B MX AND BOSSO	SUPPLY	2025 FMHUD 7		280000000.00																										"                    
MUBA MULTI CONCEPT SERVICES LIMITED (OFFICE)"					
31	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP25244082	ON-GOING CONSTRUCTION OF 50 BED MODERN DIAGNOSTIC MEDICAL CENTERS IN SULEJA, PAIKO, KUTA, MUNYA, GURARA AND GAWU BABANGIDA IN NIGER EAST.			ONGOING	SULEJA, PAIKO, KUTA, MUNYA, GURARA AND GAWU BABANGIDA IN NIGER EAST	CONSTRUCTION	2025 FMHUD 3		700000000.00																										"1. CHELIXIR NIGERIA LIMITED (OFFICE)        
2. GRANDLEGEND PLUS LIMITED (OFFICE)"					
32	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP30244039	CONSTRUCTION OF OPEN MARKET STALLS IN IJAH GBAGI COMMUNITY, TAFA LOCAL GOVERNMENT			ONGOING	TAFA	CONSTRUCTION	2025 FMHUD 6		36666000.00																										ZEDMAN GLOBAL LIMITED					
33	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP30244079	RENOVATION OF CENTRAL MOSQUE MINNA, PAIKO CENTRAL MOSQUE AND PROVISION OF CARPETS			ONGOING	 CENTRAL MOSQUE MINNA, PAIKO CENTRAL MOSQUE	CONSTRUCTION	2025 FMHUD 5		280000000.00																										"FONSOT GLOBAL SERVICES
 LIMITED (MUHAMMED SK)"					
34	FEDERAL MINISTRY OF HOUSING AND URBAN DEVELOPMENT - HQTRS (FMHUD)	ERGP8244071	CONSTRUCTION OF ULTRA MODERN SKILL ACQUISITION CENTER AT THE YOUTH CENTER IN KUTA, SHIROR0			ONGOING	KUTA	CONSTRUCTION	2025 FMHUD 2		210000000.00																										M & W RESOURCES LIMITED (YARIMA)					
35	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234909	PROVISION OF ALL-IN-ONE SOLAR STREETLIGHTS WITH HIGH BREED LUMEN AND 80 WATTS LED LIGHTS IN SOME SELECTED RURAL COMMUNITIES AND FARM IN NIGER EAST SENATORIAL DISTRICT, NIGER STATE			ONGOING	NIGER EAST SENATORIAL DISTRICT	POWER	2025 NALDA 1		140000000.00																										AICON SOLAR LIMITED (YARIMA)					PROCUREMENT PROCESS ON HOLD. AGENCY AWAITING APPROVAL
36	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234910	URGENT REHABILITATION OF DAM AND WATER TREATMENT PLANT FACILITY, INSTALLATION OF NEW EQUIPMENT, AND UPGRADE OF WATER CONTROL SYSTEM IN ILEMONA, OYUN LGA KWARA STATE			ONGOING	ILEMONA, OYUN LGA KWARA STATE (Out of catchment area)	CONSTRUCTION	2025 NALDA 2		350000000.00																										MJW PATNERS & SERVICES LIMITED (YARIMA)					
37	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234911	SUPPLY OF 14 SEATER 5 SPEED MANUAL TRANSMISSION BUSES FOR SUBSIDIZED COMMUTER SERVICES FOR BOSSO, GURARA AND SULEJA LGAS OF ZONE B, NORTH CENTRAL.			ONGOING	BOSSO, GURARA AND SULEJA 	SUPPLY	2025 NALDA 3		560000000.00																										"1. SABIRUN NIGERIA LIMITED -  (MUHAMMED SK)
2. TRADEVAULT ENTERPRISES LIMITED - (YARIMA)"					
38	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234912	PROVISION AND INSTALLATION OF MAGNETIC RESONANCE IMAGING (MRI) MACHINE USED IN RADIOLOGY SECTION IN MEDICAL DIAGNOSTICS CENTRE ZONE B, MINNA			ONGOING	CENTRE ZONE B. MINNA 	SUPPLY	2025 NALDA 6		1050000000.00																										1. DIGITEXPOINT CONCEPT LIMITED (OFFICE)                                                  2. NAS CAPITAL LIMITED                                                                                                   3. IRON FLUX LIMITED					
39	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234913	CONSTRUCTION AND PROVISION OF SOLAR BOREHOLES AND HAND PUMP BOREHOLES IN SELECTED WARDS OF RAFI, GURARA AND OTHERS.			ONGOING	RAFI, GURARA AND OTHERS.	CONSTRUCTION	2025 NALDA 5		175000000.00																										IRON FLUX LIMITED (MUHAMMED SK)					
40	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234914	SUPPLY AND PROVISION OF TRACTORS, AND UNITS OF 6 ROWS CORN SEED PLANTER MACHINE, MODEL 2BGYF-2- 5 AND (2) AND UNIT OF SEED AND FERTILIZER PLANTER SKU: BG123657 AND SPARE ACCESSORIES AND TRICYCLES FOR FARMERS IN JANGARU AND ENVIRONS.			ONGOING	JANGARU AND ENVIRONS. 	SUPPLY	2025 NALDA 9,10,11		840000000.00																										1. BLUE ELEMENT LIMITED(MUHAMMED SK)                                                                                      2. PRICE ENERGY LIMITED -( ISAAC)   					
41	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234915	PROVISION OF START UP EQUIPMENT ON INTEGRATED FARMING FOR UNEMPLOYED YOUTHS AND WOMEN AND PROVISION OF GRANT TO FARMERS IN NALDA FARMING COMMUNITIES OF KWAKUTI AND ENVIRONS NORTH CENTRAL			ONGOING	 KWAKUTI AND ENVIRONS NORTH CENTRAL	SUPPLY	2025 NALDA 12		210000000.00																										EMPTECH TECHNOLOGIES NIGERIA LIMITED (OFFICE)					
42	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234916	DEPLOYMENT OF FINDINGS OF THE RADIOLOGICAL SURVEY FOR SOIL FERTILITY MAPPING & PROVISION OF FARM INPUTS FOR MODERN PRECISION AGRICULTURAL ENHANCEMENT & SUPPLY OF IMPROVED SEEDLINGS FOR FARMING COMMUNITIES OF PADAWA, NIKUCHI IN NORTH CENTRAL			ONGOING	PADAWA, NKUCHI IN  NORTH CENTRAL	SUPPLY	2025 NALDA 13, 14		490000000.00																										1. SELSA INVESTMENT LIMITED  (OFFICE)                                                                     2. MUBA MULTI CONCEPT SERVICES LIMITED(OFFICE)					
43	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP1234917	PROVISION AND SUPPLY OF 2WD MULTIFUNCTIONAL FARM MACHINERY MINI TRACTORS 15HP 18HP; 20HP ;22HP FOR FARMERS. AND (2) PROVISION OF HOUSEHOLD AND COMMERCIAL SMALL HAND-HELD TRACTOR CORN HARVESTER - MODEL NUMBER: XD-30 FOR FARMERS IN K/KUTI AND ENVIRONS			ONGOING	K/KUTI AND ENVIRONS	SUPPLY	2025 NALDA 15, 16, 17		840000000.00																										LDE NIGERIA LIMITED (YARIMA)					
44	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP20269515	SUPPLY OF TRACTORS AND AGRICULTURAL TOOLS/IMPLEMENTS TO FARMERS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			500000000.00																										DIGITEXPOINT CONCEPT LIMITED					
45	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP20269516	PROVISION AND PROCUREMENT OF, PESTICIDES AND SEEDLING FOR FARMERS ACROSS NIGER EAST SENATORIAL DISTRICT.			ONGOING		SUPPLY			500000000.00																										SELSA LOGISTICS SERVICES LIMITED					
46	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP20269517	PROCUREMENT AND DISTRIBUTION OF FERTILISER TO FARMERS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			1000000000.00																										MJW PATNERS AND SERVICES LIMITED					
47	NATIONAL AGRICULTURAL LAND DEVELOPMENT AUTHORITY (NALDA)	ERGP20269518	CONSTRUCTION OF MINI MARKET IN SELECTED LOCATIONS IN TEGINA, MAJE, MAIKUNKELE AND OTHER LOCATIONS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			700000000.00																										NAS CAPITAL					
48	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP10243514	CONSTRUCTION, PROVISION AND INSTALLATION OF STEEL SHADE COVERS AND SOLAR LIGHTS IN ALL COTTAGE SALES OUTLETS OF VILLAGES ALONG MINNA - SULEJA ROAD.			ONGOING		CONSTRUCTION/SUPPLY	2025 NASDRA  3		245000000.00												AIM														SANEX GLOBAL LIMITED - ( OFFICE)					
49	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP10243529	PROVISION OF ALL-IN-ONE SOLAR MINI GRID AND PROVISION OF 80 WATTS LED LIGHTS STREETLIGHTS WITH HIGH BREED LUMEN IN SOME SELECTED SCHOOLS AND COMMUNITIES IN AND ENVIRONS NORTH CENTRAL ZONE.			ONGOING		SUPPLY	2025 NASDRA 10		210000000.00												AIM														BLUE ELEMENT LIMITED - (MUHAMMED SK)					
50	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP1243532	PROVISION OF TUITION AND RESEARCH GRANT TO INDIGENT SCIENCE STUDENTS IN SINGAPORE AND OTHER TERTIARY INSTITUTIONS TO INDIGENT STUDENTS TO SUPPORT THEIR LEARNING IN ICT, SCIENCES, HUMMANITIES AND VOCATIONAL EDUCATION IN SINGAPORE ZONE B, NORTH CENTRAL			ONGOING		EMPOWERMENT	2025 NASDRA 11, 12, 13, 14, 15		1120000000.00												AIM														1. OCEANBED CONSULTANTS SERVICES LIMITED - (ISAAC).                                                            2.  HERITAGEPLUS MULTI CONCEPT SERVICES - (OFFICE).                                                        3. SELSA INVESTMENT LIMITED - (OFFICE).                                                                             4. BAKUS MULTILINKS LTD - ( OFFICE).                                                                       					
51	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP30243510	CONSTRUCTION OF ICT LABORATORY, SUPPLY AND PROVISION OF SCIENCE EDUCATIONAL MATERIALS, LABORATORY EQUIPMENTS, TEACHING EQUIPMENT, SCHOOL FURNITURE AND AND FURNISHING OF ADMINISTRATIVE OFFICE BUILDING. AND PROVISION OF SCHOOL BUSES FOR SELECTED SCHOOLS IN SULEJA, BOSSO AND OTHERS			ONGOING		CONSTRUCTION/SUPPLY	2025 NASDRA 1, 2		420000000.00												AIM														1. SELSA INVESTMENT LTD - (OFFICE)                                                                 2. GRANDLEGEND PLUS LTD - ( OFFICE)  					
52	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP30243517	SUPPLY AND PROVISION OF UNITS OF ERASMART 13 INCH A3 DIGITAL 1390 DTF MODEL PRINTING MACHINE. AND UNITS OF DTF- 1200S GARMENT PRINTERS FOR YOUTH SME, (2) TRAINING IN ICT ARTIFICIAL INTELLIGENCE (AI) AND (3) PROVISION OF COMPUTERS AND LAPTOPS TO YOUTHS IN C/CHAGA ENVIRONS ZONE B NORTH CENTRAL			ONGOING		SUPPLY	2025 NASDRA 4, 5, 6		420000000.00												AIM														1. DIGITEXPOINT CONCEPT LTD - (OFFICE)                                                              					
53	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP30243523	PROVISION OF AUTOMATIC AUTOLOCKING CEMENT BLOCK MAKING MACHINE WITH CEMENT MIXER FOR BRICK PRODUCTION FOR GRADUATES EMPOWERMENT (2) AND PROVISION OF 3 NOS DULEVO 850 IS-A COMPACT STREET SWEEPER DESIGNED FOR URBAN ENVIRONS IN LIMAWA AND T/WADA.			ONGOING		SUPPLY	2025 NASDRA 7, 8		350000000.00												AIM														SABIRUN NIGERIA LIMITED - (MUHAMMED SK)            					
54	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP30243527	CONSTRUCTION, PROVISION AND INSTALLATION OF DEGRADABLE BAG AND PACKAGING MANUFACTURING FACILITIES FOR YOUNG ENTREPRENEURS IN NIGER STATE.			ONGOING		CONSTRUCTION/SUPPLY	2025 NASDRA 9		280000000.00												AIM														SYNERSIS LINEAR INTERNATIONAL LIMITED - ( YARIMA)					
55	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP8243536	SUPPLY OF SALON MOTOR VEHICLES FOR FARMERS AND 14 SEATER 5 SPEED MANUAL TRANSMISSION BUSES FOR SUBSIDIZED COMMUTER SERVICES FOR S/PAWA, GWADA AND ENVIRONS			ONGOING		SUPPLY	2025 NASDRA 16		280000000.00												AIM														ZEDMAN GLOBAL LIMITED -(OFFICE)					
56	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP8243550	TRAINING AND STRENGHENING TECHNOLOGIES SKILLS OF SMES COMPETENCY FOR SUSTAINABLE JOB CREATION IN SPACE DIGITAL ECONOMY FOR SELECTED YOUTH GRADUATES. AND TECHNOLOGY TRANSFER TRAINING IN SPACE TECHNOLOGY FOR SELECTED YOUTH GRADUATES IN ZONE B NORTH CENTRAL ZONE.			ONGOING		TRAINING	2025 NASDRA 25		140000000.00												AIM														SYNERSIS LINEAR INT'L LIMITED					
57	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP30243543	PROCUREMENT AND INSTALLATION OF (1)ECHOCARDIOGRAPHY, (2)BRONCOSCOPY AND (3) ENDOSCOPY MACHINES (4)  X-RAY MEDICAL EQUIPMENT 30 HANDHELD DIGITAL X RAY MACHINE ALL IN ONE DR SYSTEM WITH FLAT PANEL DETECTOR MODEL NO. MSLGX88. (5)MEDICAL DOUBLE CRANK ABS BED WITH PLASTIC RAILS, MATTRESSES, PILLOWS AND BEDSHEETS  (6) WHEEL CHAIRS FOR DISABLES, (7) OTHER MEDICAL EQUIPMENT FOR IBB SPECIALIST HOSPITAL CHANCHAGA.			ONGOING		SUPPLY	2025 NASRDA 19, 20, 21		910000000.00												AIM														1. FIRETECH CONCEPT LTD - (YARIMA)                                       2. HERITAGEPLUS MULTI CONCEPT LIMITED - (OFFICE)                                                  3.  EMPTECH TECHNOLOGIES NIG LTD - (OFFICE)                                          					
58	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275444	RENOVATION AND FENCING OF SULEIMAN BARON TECHNICAL SCHOOL IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION	MAY BE LINKED TO 2025 NASRDA (17), BUT 2025 NASRDA (17) IS A ZIP PROJECT. CLARIFICATION IS THUS REQUIRED		500000000.00												AIM														BLUE ELEMENT LIMITED					
59	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275445	SUPPLY AND INSTALLATION OF SOLAR PV STORAGE ALL IN ONE MACHINE AND SOLAR STREETLIGHTS IN SELECTED SECONDARY SCHOOLS, BURIAL GROUND, HOMES AND MARKET IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			600000000.00												AIM														AICON SOLAR LIMITED					
60	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275446	CONSTRUCTION AND UPGRADING OF SPORTS FACILITY CENTRE IN SELECTED LOCATION IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			1500000000.00												AIM														1. M&W RESOURCES LIMITED                                                                                                                                              2. NAS CAPITAL LIMITED					
61	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275447	CONSTRUCTION OF PERIMETERFENNCE AT SULEIMAN BARAU TECHNICAL COLLEGE SULEJA IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			500000000.00												AIM														CHELIXIR NIGERIA LIMITED					
62	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275448	SUPPLY OF HOSPITAL EQUIPMENT AND FURNITURE FOR HEALTH INSTITUTIONS ACROSS NIGEREAST SENATORIAL DISTRICT			ONGOING		SUPPLY			300000000.00												AIM														ZEDMAN GLOBAL LIMITED					
63	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275450	CONSTRUCTION OF HAND-PUMPS BOREHOLES ACROSS NIGER EAST SENATORIAL DISTRICT.			ONGOING		CONSTRUCTION			500000000.00												AIM														SKD-GOLDEN GATE LIMITED					
64	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275451	PROVISION OF STUDY GRANT TO INDIGENT MEDICAL AND TECHNOLOGY STUDENTS AT YAN’AN MEDICAL COLLEGE UNIVERSITY CHINA AND SANSKARAM UNIVERSITY INDIA FOR INDIGENT CONSTITUENTS OF NIGER EAST SENATORIAL DISTRICT			ONGOING		EMPOWERMENT			1500000000.00												AIM														1. BAKUS MULTI-LINKS SERVICES LIMITED                               2. ZEDMAN GLOBAL LIMITED                                                                                         3. SELSA INVESTMENT LIMITED					
65	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275480	SUPPLY, INSTALLATION AND COMMISSIONING OF MEDICAL ANESTHESIA MACHINE, OPERATING TABLE, MEDICAL ICU RESPIRATOR VENTILATOR, DISPLAY MEDICAL MULTI- PARAMETER PATIENT MONITOR, MEDICAL ECG MACHINE 12- CHANNEL ELECTROCARDIOGRAPH, MEDICAL ECG MACHINE 12-CHANNEL ELECTROCARDIOGRAPH, ARGON PLASMA COAGULATION ELECTROSURGICAL UNIT, AUTOMATIC HIGH FREQUENCY, BLOOD BAG TUBE SEALER FOR HOSPITALS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			750000000.00												AIM														HASHTAG TECHNOLOGY LIMITED					
66	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275481	PROVISION OF WATER TANK TRUCKS FOR EMERGENCY WATER DISTRIBUTION IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			750000000.00												AIM														DIGITEXPOINT CONCEPT LIMITED					
67	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ERGP20275482	PROVISION OF GRANT TO VULNERABLE AND SME SUPPORT IN NIGER EAST SENATORIAL DISTRICT			ONGOING		EMPOWERMENT			750000000.00												AIM														SENSITIVE LOGISTICS SERVICES LIMITED					
68	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ZIP20250907	CONSTRUCTION/RENOVATION OF GOVT TECHNICAL SCIENCE SCHOOL SULEJA LAB. SUPPLY OF SCIENCE EDUCATIONAL MATERIALS,LAB, EQUIPMENTS,TEACHING EQUIPMENT,SCHOOL FURNITURE SULEJAM NIGER EAST 			ONGOING		CONSTRUCTION	MAY BE LINKED TO 2025 NASRDA 1, 17. CLARIFICATION IS REQUIRED		500000000.00												AIM														M&W RESOURCES LIMITED					
69	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ZIP20260978	PROMOTION RENEWAL ENERGY ENTREPREMEUSHIP THROUGH PRACTICAL SOLAR INSTALLATION AND MAINTENANCE TRAINING FOR YOUTHS IN NIGER EAST SENATORIAL DISTRICTM NIGER STATE 			NEW		TRAINING			100000000.00												AIM														IRON FLUX LIMITED					
70	NATIONAL SPACE RESEARCH AND DEVELOPMENT AGENCY - ABUJA (NASRDA)	ZIP20260979	RENOVATION OF SELECTED CLASSROOMS IN PAIKORO AND CHANCHAGA LGAs IN NIGER EAST SENATORIAL DISTRICT IN NIGER STATE 			NEW		CONSTRUCTION			100000000.00												AIM														BLUE ELEMENT LIMITED					
71	NATIONAL CENTRE FOR WOMEN DEVELOPMENT (NCWD)	ERGP22243384	ESTABLISHMENT OF AGRO-PROCESSING FACILITIES FOR AGROPRENEURS IN 3 SELECTED LOCATIONS OF GARAM INDUSTRIAL ZONE			ONGOING	JANGARU II, MAIKUNKELE, JANGARU I - GARAM INDUSTRIAL ZONE	SUPPLY\EMPOWERMENT	2025 NCWD 1		700000000.00																										BLUE ELEMENT LIMITED					
72	NATIONAL CENTRE FOR WOMEN DEVELOPMENT (NCWD)	ERGP22243394	PURCHASE OF COOKING GAS FOR RURAL WOMEN IN NIGER EAST SENATORIAL DISTRICT AND GIRL- CHILD SCHOLARSHIP FOR INDIGENT STUDENTS FROM P/KORO, CHANCHAGA, AND OTHERS			ONGOING	CHANCHAGA	SUPPLY\EMPOWERMENT	2025 NCWD 3		350000000.00																										IRON FLUX LIMITED					
73	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP23245360	SUPPLY OF SEWING, GRINDING/ FOOD PROCESSING MACHINE FOR WOMEN IN P/KNUKNU, BONU, GWAM AND ENVIRONS			ONGOING		SUPPLY	2025 NDE 9, 10, 11		210000000.00																										1. BAKUS MULTILINKS NIG LTD - (OFFICE)                                                                              2. ZEDMAN GLOBAL SERVICES - (OFFICE)                                                                                           					
74	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP23245383	PROVISION OF EDUCATIONAL GRANT TO INDIGENT STUDENTS TO SUPPORT LEARNING IN ICT, MATHEMATICS AND SCIENCE EDUCATION IN NIGER EAST SENATORIAL DISTRICT			ONGOING		EMPOWERMENT	2025 NDE 1, 2		140000000.00																										1. TRADEVAULT ENTERPRISES LTD -  (YARIMA)                                                           2.  NAS CAPITAL LIMITED - (YARIMA)      					
75	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP29245388	SUPPLY OF COMPUTERS, PRINTERS, SOLAR PANELS AND INVERTERS, IPS AND OTHER IT EQUIPMENT/ CONTRUCTION OF PERIMETER FENCING, GATE HOUSE AND BOREHOLE WITH OVER HEAD TANKS, AND FURNISHINGS TO CBT CENTERS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY	2025 NDE 7, 8		140000000.00																										1. LIGTH BOX TECHNOLOGY NIGERIA LIMITED -(YARIMA)                                                         2. EMPTECH TECHNOLOGIES NIGERIA LTD - (OFFICE)					
76	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP8245374	VOCATIONAL TECHNICAL TRAINING AND SKILL ACQUISITION FOR YOUNG GRADUATES AND PROVISION OF STARTER PACKS TO WOMEN AND YOUTHS IN NIGER EAST SENATORIAL DISTRICT.			ONGOING		TRAINING	2025 NDE 3		175000000.00																										MJW PATNERS AND SERVICES LIMITED					
77	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP8245380	PURCHASE AND SUPPLY OF TRICYCLES AND MOTORCYCLES TO SELECTED YOUTHS IN GURARA, MUNYA AND PAIKORO LGAS.			ONGOING		SUPPLY			140000000.00																										FIRETECH CONCEPTS LIMITED					
78	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP20275318	SUPPLY OF GRINDING MACHINE, MECHANICAL AND PLUMBING TOOL- BOXES AND START-UP EQUIPMENT TO SELECTED YOUTHS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		SUPPLY			500000000.00	487500000.00																								A7	SELSA LOGISTICS SERVICES LIMITED - (OFFICE)	OCEANIC WORLD SERVICES SYSTEM LIMITED - (OFFICE)		TECHNICAL SUBMISSION DONE 1ST JUNE 2026. 	FINANCIAL SUBMISSION DONE 1ST JUNE 2026	
79	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP20275319	SKILL ACQUISITION, MANPOWER DEVELOPMENT, AND ENTREPRENEURSHIP TRAINING (A)			ONGOING		TRAINING			88500000.00	87750000.00																							C7 - TRAINING                                        A8 - SUPPLY	C7                                          A8	FIRETECH CONCEPT LTD - (YARIMA)	LAITH COMPANY LTD - (YARIMA)		TECHNICAL SUBMISSION DONE 18TH MAY 2026. 	FINANCIAL SUBMISSION DONE 1ST JUNE 2026	
80	NATIONAL DIRECTORATE OF EMPLOYMENT (NDE)	ERGP20275319	 AND PROVISION OF START UP TOOLS FOR FARMERS, YOUTHS, AND WOMEN ACROSS NIGER EAST SENATORIAL DISTRICT(B)			ONGOING		TRAINING			241500000.00	240750000.00																							C7 - TRAINING                                        A8 - SUPPLY	C7                                          A8	LAITH COMPANY LTD - (YARIMA)	FIRETECH CONCEPT LTD - (YARIMA)		TECHNICAL SUBMISSION DONE 18TH MAY 2026. 	FINANCIAL SUBMISSION DONE 1ST JUNE 2026	
81	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241875	PROVISION OF HOSPITAL EQUIPMENT AND APPLIANCES FOR PHC AND RURAL HOSPITALS IN MX, SULEJA AND KAGARA 			ONGOING	KAGARA	SUPPLY	2025 NIHORT 1, 2, 3		420000000.00																										1. DIGITEXPOINT CONCEPT LTD - (OFFICE)                                                 2. EMPTECH TECHNOLOGIES NIGERIA LTD - (OFFICE)                                                                  3. OCEANBED CONSULTANTS SERVICES LTD - (ISAAC)					
82	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241879	DESIGN AND CONSTRUCTION OF PROTOTYPE 50 STALLS CAPACITY RURAL MARKET FACILITY IN CHIMBI, GWADA AND DANDAUDU			ONGOING	CHIMBI, GWADA & DANDAUDU	CONSTRUCTION	2025 NIHORT 4		210000000.00																										GRANDLEGEND PLUS LTD - (OFFICE)					
83	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241883	RENOVATION OF EMIRS PALACES IN THE EMIRATE COUNCILS OF ZONE B NIGER STATE			ONGOING	ZONE B NIGER STATE	CONSTRUCTION	2025 NIHORT 6		560000000.00																										BLUE ELEMENT LIMITED - (MUHAMMED SK)					
84	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241889	RENOVATION OF ETSU NUPE PALACE BIDA EMIRATE COUNCIL (NIGER EAST)			ONGOING	BIDA	CONSTRUCTION	2025 NIHORT 7		350000000.00																										MJW PARTNERS & SERVICES LTD - (YARIMA)					
85	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241894	PROVISION OF UTILIYY VEHICLES FOR DISTRICT VIGILANTES, SECURITY AND OTHERS ACROSS NIGER EAST SENATORIAL DISTRICT.			ONGOING	NIGER EAST 	SUPPLY	2025 NIHORT 8, 9, 10		420000000.00																										1. PRICE ENERGY LIMITED - ISAAC)                                                          2.TRADEVAULT ENTERPRISES LTD -(YARIMA)  					
86	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241897	DESIGN AND CONSTRUCTION OF PROTOTYPE 50 STALLS CAPACITY RURAL MARKET FACILITY IN MAIKUNKELE AND JAZU.			ONGOING	MAIKUNKELE & JAZU	CONSTRUCTION	2025 NIHORT 5		210000000.00																										SANEX GLOBAL LOGISTICS SERVICES LTD - (OFFICE)					
87	NATIONAL HORTICULTURAL RESEARCH INSTITUTE- IBADAN (NIHORT)	ERGP30241902	RENOVATION OF SOME SELECTED SPORTS FACILITIES AND PROVISION OF BOAT FOR SHIRORO COMMUNITY.			ONGOING	SHIRORO	CONSTRUCTION/SUPPLY	2025 NIHORT 11		560000000.00																										SYNERSIS LINEAR INTERNATIONAL LIMITED - (YARIMA)					
88	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP30244725	PROVISION OF EMPOWERMENT ITEMS FOR YOUTHS AND WOMEN IN NIGER EAST SENATORIAL DISTRICT.			ONGOING		EMPOWERMENT	2025 NPC 3		140000000.00																										TAWMAN GLOBAL CONCEPT LIMITED					
89	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP30244729	SUPPLY AND PROVISION OF MECHANICAL, ELECTRICAL AND MASONARY TOOL BOXES FOR YOUNG GRADUATES SKILLS ACQUISITION IN MSM - NIGER STATE			ONGOING		SUPPLY	2025 NPC 1 & 2		350000000.00																										CHELIXIR NIGERIA LIMITED -  (OFFICE)                                                  					
90	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP20275062	PROVISION OF RESEARCH EQUIPMENT FOR SCIENCE, TECHNOLOGY, ENGINEERING, AND MATHEMATICS (STEM) PROGRAMMES LABORATORIES IN SELECTED INSTITUTIONS, AND PROVISION OF TERTIARY EDUCATIONGRANTS TO 200 STUDENTS FROM NIGER EAST SENATORIAL DISTRICT PURSUING MEDICAL AND TECHNOLOGY ENGINEERING RELATED STUDIES IN INDIA AND CHINA.			ONGOING		SUPPLY			70000000.00																										OCEANIC WORLD SYSTEMS SERVICES LIMITED					
91	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP20275063	REMODELLING, INSTALLATION, AND FULL EQUIPPING OF COMPUTERBASED TEST (CBT) CENTRES IN SELECTED LOCATIONS ACROSS THE NIGER EAST SENATORIAL DISTRICT.			ONGOING		CONSTRUCTION	2025 NPC 4		210000000.00																										FONSOTS GLOBAL SERVICES LIMITED					
92	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP20275064	SUPPLY OF MRI MACHINE AND OTHE DIAGNOSTIC EQUIPMENT TO HEALTHCARE CENTRES IN NIGER EAST			ONGOING		SUPPLY			70000000.00																										PAUMATECH NIGERIA LIMITED					
93	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP20275068	INSTALLATION AND FULL EQUIPPING OF COMPUTER-BASED TEST (CBT) CENTRES IN ILEMONA, OYUN LGA KWARA STATE.			ONGOING		SUPPLY	2025 NPC 6		140000000.00																										BLUE ELEMENT LIMITED					
94	NATIONAL PRODUCTIVITY CENTRE (NPC)	ERGP20275095	REHABILITATION OF HABIBU SHUAIBU SPORT COMPLEX MINNA IN NIGER EAST SENATORIAL DISTRICT NIGER STATE			ONGOING		CONSTRUCTION	2025 NPC 5		175000000.00																										DEEQMA GLOBAL RESOURCES LIMITED					
95	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246765	CONSTRUCTION OF SILOS STORAGE FACILITY, FENCING, STORAGE 1000KVA GENERATOR AND GENERATOR HOUSE, INCLUDING SOLAR POWERED BOREHOLE, PERIMETER AND GATE JANGARU NORTH CENTRAL ZONE			ONGOING	JANGARU, NORTH CENTRAL ZONE	CONSTRUCTION	2025 NSPRI 6		350000000.00																										M & W RESOURCES LTD (YARIMA)                                  					
96	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246815	CONSTRUCTION, PROVISION AND INSTALLATION OF 80T/BATCH PARBOILED RICE PLANT WITH 100T/D RICE MILLING PRODUCTION LINE WITH STEEL SHELTER AND WAREHOUSE IN JANGARU, NORTH CENTRAL ZONE.			ONGOING	JANGARU, NORTH CENTRAL ZONE	CONSTRUCTION	2025 NSPRI 1		1750000000.00																										GRANDLEGEND PLUS LTD (OFFICE)					
97	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246816	CONSTRUCTION OF SILOS STORAGE FACILITY, FENCING, STORAGE 1000KVA GENERATOR AND GENERATOR HOUSE, INCLUDING SOLAR POWERED BOREHOLE, PEREMETER AND GATE IN JANGARU NORTH CENTRAL ZONE.			ONGOING	JANGARU, NORTH CENTRAL ZONE	CONSTRUCTION	2025 NSPRI 7		1750000000.00																										SKD-GOLDEN GATE CONCEPT LTD (YARIMA)					
98	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246823	CONSTRUCTION, SUPPLY AND INSTALLATION OF COMPLETE SHEA AND SESSAME SEED PROCESSING AND MILLING MACHINE AT THE MINNA AIRORT AGRO PROCESSING ZONE.			ONGOING	MINNA AIRPORT	CONSTRUCTION	2025 NSPRI 12		420000000.00																										OCEANBED CONSULTANT SERVICES                                                      					
99	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246824	PROVISION OF UREA FERTILIZERS TO RICE, FARMERS, COOPERATIVE GROUP FARMERS, NOMAN RANI FARMERS AND OTHER FARMING COMMUNITTIES IN P/KORO, SHIRORO, TAFA, RAFI, K/KORO, TATITKO, BEJI, FUKA, BAIDNA, F/DOKI AND ENVIRONS			ONGOING	 P/KORO, SHIRORO, TAFA, RAFI, K/KORO, TATITKO, BEJI, FUKA, BAIDNA, F/DOKI AND ENVIRONS	SUPPLY	2025 NSPRI 13		140000000.00																										BLUE ELEMENT LTD-(MUHAMMED SK)					
100	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246825	CONSTRUCTION OF AGRO WAREHOUSE, MAIZE FLOUR MILL, STEEL SHELTER AND GROUNDNUT OIL PRESS MILL AND MODERN ABBATOIR WITH SOLAR BOREHOLES IN AIRPORT AGRO CITY JANGARU .			ONGOING	AIRPORT AGRO CITY JANGARU	CONSTRUCTION	2025 NSPRI 14		490000000.00																										M&W RESOURCES LIMITED-(YARIMA)					
101	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246826	PROVISION OF UREA FERTILIZERS TO COOPERATIVE GROUP FARMERS IN T/MALLAM, AMALE, MUNYA,TUTUNGO, SHATA, MAJE, GBASEGO, JEDNA, KWAGANA AND JERE			ONGOING	T/MALLAM, AMALE, MUNYA,TUTUNGO, SHATA, MAJE, GBASEGO, JEDNA, KWAGANA AND JERE	SUPPLY	2025 NSPRI 15		700000000.00																										TAWMAN GLOBAL CONCEPT SERVICES LIMITED-(OFFICE)					
102	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246827	PROVISION OF RESEARCH GRANT TO INDIGENT SCIENCE STUDENTS IN SPECIALISED COURSES IN TERTIARY INSTITUTIONS IN SINGAPORE STUDYING ARTIFICIAL INTELLIGENCE (AI) IN ICT, SCIENCES, AND VOCATIONAL EDUCATION FROM ZONE B. PAIDA			ONGOING	ZONE B. PAIDA 	EMPOWERMENT	2025 NSPRI 17		1120000000.00																										OCEANBED CONSULTANT SERVICES     (ISAAC)                                                        					
103	NIGERIA STORED PRODUCTS RESEARCH, ILORIN	ERGP1246828	CONSTRUCTION AND PROVISION OF HAND PUMP BOREHOLES IN SELECTED COMMUNITIES IN TAFA AND RAFI.			ONGOING	TAFA, RAFI	CONSTRUCTION	2025 NSPRI 21		140000000.00																										AICON CIVIL ENGINEERING LIMITED-(YARIMA)					
104	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243555	PROVISION AND CONNECTION OF 133 KW ELECTRICITY TO SHATA, PYATA AND KADO COMMUNITIES IN NIGER EAST SENATORIAL DISTRICT.			ONGOING	SHATA, PYATA & KODO COMMUNITIES	POWER	2025 REA 7		175000000.00												CS														SYNERSIS LINEAR INT'L LIMITED  (YARIMA)					
105	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243607	SUPPLY AND INSTALATION OF 300KVA AND 500KVA TRANSFORMERS FOR SOME SELECTED COMMUNITIES IN RAFI, PANDOGARI, MAKERA, GAWU, JANGARU, MAIKUNKELE AND OTHERS			ONGOING	RAFI, PANDOGARI, MAKERA, GAWU, MAIKUNKELE, B/SALE	POWER	2025 REA 1		350000000.00												CS														PRICE ENERGY LIMITED (ISAAC)					
106	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243617	ELECTRIFICATION AND CONNECTING TO NATIONAL GRID OF CHIMBI, A/KUBEWA, TATIKO, PAKHAPI, U/MADAKI KONGOMA CENTRAL, U/MALLAM LABBO, PRISON QUARTERS AND PADUKWAI/B/SALE			ONGOING	CHIMBI-U-KUBEWA, U/MADAKI-KOGAMA PANDOGARI, YAPAPI- PADUKWAI	POWER	2025 REA 2		210000000.00												CS														LDE NIG LIMITED (YARIMA)					
107	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243621	CONSTRUCTION AND INSTALLATIONOF SOLAR MINI GRID AND ALL-IN-ONE SOLAR STREETLIGHTS WITH HIGH BREED LUMEN AND 80 WATTS LED LIGHTS IN SOME SELECTED RURAL COMMUNITIES U/GABAS, IZOM AND KPAKUNGU ZONE B			ONGOING	KPAKUNGU ZONE B, U/GABAS/U/YAMMA,  IZOM PHC, GOVT SCIENCE SCHOOL, KPAKUNGU PHC (70kWp), MINNA INSTITUTE OF TECHNOLOGY (300kWP)	POWER	2025 REA 3		840000000.00												CS														M&W RESOURCES LIMITED (YARIMA)					
108	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243647	ON-GOING CONSTRUCTION OF 50 BED MODERN DIAGNOSTIC MEDICAL CENTERS IN SULEJA, PAIKO, KUTA, MUNYA, GURARA AND GAWU BABANGIDA IN NIGER EAST			ONGOING	SULEJA, PAIKO, KUTA, MUNYA, GURARA AND GAWU BABANGIDA IN NIGER EAST	CONSTRUCTION	2025 REA 9		560000000.00												CS														M&W RESOURCES LIMITED					
109	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243652	PROVISION AND INSTALLATION OF MINI SOLAR GRIDS TO BOOST POWER IN SELECTED SMEs AND AGRO PROCESSING LOCATIONS IN JANGARU, G/KWANO AND OTHER LOCATIONS IN MX ZONE B.			ONGOING	GENERAL HOSPITAL EXTENSION (250kWp), FGC MINNA (300kWp),GIDAN KWANO SCHOOL PROJECT (50kWP),  IBB SPECIALIST HOSPITAL (200kWP), GENERAL HOSPITAL MINNA (200kWP), 	POWER	2025 REA 4		2100000000.00												CS														1. BLUE ELEMENT LIMITED                                                                  2. M&W RESOURCES LIMITED                                                                                      3.LAITH COMPANY LIMITED					
110	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243657	PROVISION OF ALL-IN-ONE SOLAR 80 WATTS LED LIGHTS STREETLIGHTS WITH HIGH BREED LUMEN IN SOME SELECTED FARMING COMMUNITIES IN NIGER EAST ENVIRONS NORTH CENTRAL ZONE.			ONGOING	 NIGER EAST ENVIRONS NORTH CENTRAL ZONE	POWER	2025 REA 5		210000000.00												CS														MJW PATNERS AND SERVICES LIMITED					
111	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243660	REHABILITATION OF 40KVA SOLAR SYSTEM AT KWAMBA, SULEJA LGA NIGER EAST SENATORIAL DISTRICT			ONGOING	KWAMBA, SULEJA LGA	POWER	2025 REA 6		28000000.00												CS														PAUMATECH NIGERIA LIMITED					
112	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP10243667	PROVISION AND INSTALLATION OF TRANSFOMERS TO SELECTED COMMUNITIES IN SULEJA/TAFA/GURARA, NIGER STATE			ONGOING	SULEJA/TAFA/GURARA	POWER			140000000.00												CS														FONSOTS GLOBAL SERVICES LIMITED					
113	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP20276770	INSTALLATION AND PROVISION OF MINI-GRID AND SOLAR POWERED STREETLIGHTS IN SELECTED LOCATIONS IN NIGER EAST SENATORIAL DISTRICT.			ONGOING	NIGER EAST 	POWER			1300000000.00												CS														HERITAGEPLUS MULTI CONCEPT SERVICES LIMITED					
114	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP20276784	CONSTRUCTION OF A SOLAR-HYBRID MINI-GRID AND PROVISION OF SOLAR STREET LIGHTS IN SELECTED LOCATIONS IN NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST 	POWER	2025 N-HYPHADEC 1		700000000.00												CS														EMPTECH TECHNOLOGIES NIGERIA LIMITED					
115	NATIONAL RURAL ELECTRIFICATION AGENCY (NREA)	ERGP20276785	SUPPLY AND INSTALLATION OF SOLAR MINI-GRID AND SOLAR STREETLIGHTS IN SELECTED SECONDARY SCHOOLS, BURIAL GROUNDS AND MARKETS IN NIGER EAST SENATORIAL DISTRICT			ONGOING	NIGER EAST 	POWER			750000000.00												CS														HASHTAG TECHNOLOGY LIMITED					
116	UNIVERSAL BASIC EDUCATION COMMISSION (UBEC) 	ERGP23235428	CONSTRUCTION OF 2 STOREY BUILDING BLOCKS OF 3 CLASSROOMS WITH TOILETS EACH IN KATO AND OTHER SELECTED LOCATIONS.			ONGOING		CONSTRUCTION	2025 UBEC 1, 2		700000000.00																										1. MJW PATNERS &SERVICES LTD - (YARIMA)                                              2. BLUE ELEMENT LTD  - (MUHAMMED SK)            					
117	UNIVERSAL BASIC EDUCATION COMMISSION (UBEC) 	ERGP23235429	RENOVATION AND UPGRADE OF SCHOOLS AND PROVISION OF MODERN LEARNING AND TEACHING EQUIPMENT FOR RAFI AND P/KORO. / RENOVATION AND FURNISHING OF SELECTED PRIMARY AND SECONDARY SCHOOLS IN P/KORO, RAFI AND KUTA, BEJI, T/ MALLAM, KWAKUTI, IZOM AND G/KWANO TUNGA.			ONGOING		CONSTRUCTION	2025 UBEC 3, 4, 5		490000000.00																										1. IBG CONSTRUCTION AND ASSOCIATE SERVICES LTD - (YARIMA)                                                      2. GRANDLEGEND PLUS LTD-(OFFICE)                                                     3. GRANDLEGEND PLUS LTD-(OFFICE)                    					
118	UNIVERSAL BASIC EDUCATION COMMISSION (UBEC) 	ERGP20277494	RENOVATION AND FURNISHING OF SELECTED PRIMARY AND SECONDARY SCHOOLS ACROSS NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			500000000.00																										SYNERSIS LINEAR INT'L LIMITED					
119	FEDERAL MINISTRY OF WORKS (FMW)	ERGP20276857	RECONSTRUCTION OF SULEJA TO MINNA ROAD (DIKKO TO MAJE BYPASS) IN NIGER EAST SEN. DISTRICT, NIGER STATE			ONGOING	DIKKO, MAJE BYPASS	CONSTRUCTION	2025 FMW 1		10500000000.00																										M&W RESOURCES LIMITED					
120	HYDRO-ELECTRIC POWER PRODUCING AREAS DEVELOPMENT COMMISSION (HYPPADEC)	ERGP20270035	PROVISION AND PROCUREMENT OF FARM IMPLEMENT, FERTILISER, PESTICIDES AND SEEDLING FOR FARMERS ACROSS NIGER EAST SENATORIAL DISTRICT.			ONGOING		SUPPLY			300000000.00																									LOT B2	MJW PARTNERS & SERVICES LIMITED (YARIMA)	"1.       MUBA MULTI CONCEPT SERVICES LIMITED                                
2.        SELSA INVESTMENT LTD
3.        SKD GOLDEN GATE LTD
4.        HERITAGE PLUS MULTI CONCEPT SERVICES LTD
"				
121	HYDRO-ELECTRIC POWER PRODUCING AREAS DEVELOPMENT COMMISSION (HYPPADEC)	ERGP20270036	CONSTRUCTION OF SOLAR POWERED BOREHOLES ACROSS NIGER EAST SENATORIAL DISTRICT.			ONGOING		CONSTRUCTION			500000000.00																									LOT A3	FIRETECH CONCEPTS LTD	"1.       DIGITEXPOINT CONCEPT LIMITED
2.        TAWMAN NIG LTD
3.       INTERNATIONAL TIME TRAVELLERS LTD
4.      CLEMEDE PATHAGE LIMITED
"				
122	HYDRO-ELECTRIC POWER PRODUCING AREAS DEVELOPMENT COMMISSION (HYPPADEC)	ERGP20270037	CONSTRUCTION OF BRIDGE AND EXPANSION OF GWAM MINI- DAM IN NIGER EAST SENATORIAL DISTRICT.			ONGOING		CONSTRUCTION			300000000.00																									LOT A4	SYNERSIS LINEAR INT'L LIMITED (YARIMA)	"1.        NAS CAPITAL LIMITED
2.        MUBA MULTI CONCEPT SERVICES LIMITED
3.        ZITEK ENGINEERING LIMITED
4.        NESPRESCO SERVICES LIMITED
"				
123	HYDRO-ELECTRIC POWER PRODUCING AREAS DEVELOPMENT COMMISSION (HYPPADEC)	ERGP20270038	SURGICAL AND OPTHALMOLOGICAL OUTREACHES TO VULNERABLE CONSTITUENTS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		EMPOWERMENT			500000000.00																									LOT C1	CHELIXIR NIGERIA LIMITED (OFFICE) 	"1.        ZEDMAN GLOBAL
2.       SKD GOLDEN GATE LTD
3.        TAWMAN NIG LTD
4.        CLOAKS AND CLEMEDE
"				
124	HYDRO-ELECTRIC POWER PRODUCING AREAS DEVELOPMENT COMMISSION (HYPPADEC)	ERGP20270039	CONSTRUCTION OF 2 AND 3 BEDROOMS HOUSING UNITS FOR LOW INCOME AND VULNERABLE IN SELECTED LOCATIONS IN NIGER EAST SENATORIAL DISTRICT			ONGOING		CONSTRUCTION			3300000000.00																									LOT A6	1.M&W RESOURCES LIMITED (YARIMA)\n2. GRANDLEGEND PLUS LIMITED (OFFICE)\n3. SELSA LOGISTICS SERVICES LIMITED (OFFICE)	"1.        HERITAGE PLUS MULTI CONCEPT SERVICES LTD
2.        OCEANIC WORLD SYSTEMS SERVICES LIMITED
3.        IBG CONSTRUCTION LTD
4.        BAKUS MULTILINKS SERVICES LTD
5.        MIFFLIN GLOBAL LIMITED
6.        HYDRAXO ENERGIES TECHNOLOGIES LIMITED
7.        FAKUBS GLOBAL RESOURCES LTD
"
"""

def parse_amount(val_str):
    if not val_str:
        return Decimal('0.00')
    cleaned = re.sub(r'[^\d\.]', '', str(val_str).strip())
    if not cleaned:
        return Decimal('0.00')
    try:
        return Decimal(cleaned)
    except:
        return Decimal('0.00')

def get_or_create_category(cat_raw):
    cat_raw = (cat_raw or '').strip().upper()
    name_map = {
        'POWER': 'Power',
        'CONSTRUCTION': 'Construction',
        'CONSTRUCTION/SUPPLY': 'Construction',
        'SUPPLY\\EMPOWERMENT': 'Supply',
        'SUPPLY/EMPOWERMENT': 'Supply',
        'TRAINING': 'Training',
        'SUPPLY': 'Supply',
        'EMPOWERMENT': 'Empowerment',
    }
    cat_name = name_map.get(cat_raw, 'Construction')
    cat_obj, _ = ProjectCategory.objects.get_or_create(name=cat_name, defaults={'description': f'{cat_name} Projects'})
    return cat_obj

def get_project_type(cat_raw):
    cat_raw = (cat_raw or '').strip().upper()
    if 'CONSTRUCTION' in cat_raw:
        return 'CONSTRUCTION'
    return 'SUPPLY_TRAINING'

def load_2026_projects():
    # Fee types
    fee_facilitation, _ = FeeType.objects.get_or_create(name='Facilitation Fee (PR)', defaults={'description': 'Facilitation Fee (PR)'})
    fee_logistics, _ = FeeType.objects.get_or_create(name='Logistics and Monitoring', defaults={'description': 'Logistics and Monitoring Fee (10% of Contract Amount)'})

    # Users
    cs_user, _ = User.objects.get_or_create(username='CS', defaults={'first_name': 'CS', 'is_staff': True})
    aim_user, _ = User.objects.get_or_create(username='AIM', defaults={'first_name': 'AIM', 'is_staff': True})
    eta_user, _ = User.objects.get_or_create(username='ETA', defaults={'first_name': 'ETA', 'is_staff': True})
    amo_user, _ = User.objects.get_or_create(username='A.M.O', defaults={'first_name': 'A.M.O', 'is_staff': True})

    user_map = {
        'CS': cs_user,
        'AIM': aim_user,
        'ETA': eta_user,
        'A.M.O': amo_user,
    }

    # 2026 Timestamp
    dt_2026 = datetime.datetime(2026, 6, 1, 12, 0, 0, tzinfo=datetime.timezone.utc)

    lines = [l.strip() for l in RAW_DATA.strip().split('\n') if l.strip()]
    
    # Simple tab-based line parser taking care of multiline quoted fields if any
    parsed_rows = []
    current_row = None

    for line in RAW_DATA.strip().split('\n'):
        if not line.strip():
            continue
        parts = line.split('\t')
        if parts[0].isdigit() and len(parts) >= 4:
            if current_row:
                parsed_rows.append(current_row)
            current_row = parts
        else:
            if current_row:
                current_row[-1] += "\n" + line

    if current_row:
        parsed_rows.append(current_row)

    print(f"Total parsed 2026 rows: {len(parsed_rows)}", flush=True)

    imported_count = 0

    for row in parsed_rows:
        with transaction.atomic():
            # Pad row if missing columns
            while len(row) < 43:
                row.append('')

            sn_val = row[0].strip()
            mda = row[1].strip()
            project_code = row[2].strip()
            project_name = row[3].strip()
            plain_boq = row[4].strip()
            drawing_design = row[5].strip()
            type_str = row[6].strip()
            location = row[7].strip()
            category_raw = row[8].strip()
            linked_project = row[9].strip()
            award_letter_and_boq = row[10].strip()
            budget_amount = parse_amount(row[11])
            actual_contract_amount = parse_amount(row[12])
            admin_fee = parse_amount(row[13])
            facilitation_fee_raw = parse_amount(row[14])
            logistics_fee_raw = parse_amount(row[15])
            batch_no_mobilization = row[16].strip()
            mobilization_received = parse_amount(row[17])
            batch_no_final_payment = row[19].strip()
            amount_paid = parse_amount(row[20])
            in_house_benchmark = parse_amount(row[21])
            cost_percentage = parse_amount(row[22])
            staff_assigned_key = row[23].strip()
            subcontractor_raw = row[24].strip()
            
            lot = row[36].strip()
            final_companies = row[37].strip()
            back_up_companies = row[38].strip()
            technical = row[40].strip()
            financials = row[41].strip()
            remarks = row[42].strip()

            category_obj = get_or_create_category(category_raw)
            proj_type = get_project_type(category_raw)
            staff_obj = user_map.get(staff_assigned_key)

            # Facilitation Fee
            fac_fee = facilitation_fee_raw if facilitation_fee_raw > 0 else Decimal('16000.00')

            # Logistics Fee (10% of actual contract amount if not specified)
            if logistics_fee_raw > 0:
                log_fee = logistics_fee_raw
            elif actual_contract_amount > 0:
                log_fee = actual_contract_amount * Decimal('0.10')
            else:
                log_fee = Decimal('0.00')

            # Build remarks text
            remarks_parts = []
            if linked_project:
                remarks_parts.append(f"Linked Project: {linked_project}")
            if plain_boq:
                remarks_parts.append(f"BOQ: {plain_boq}")
            if drawing_design:
                remarks_parts.append(f"Drawing: {drawing_design}")
            if award_letter_and_boq:
                remarks_parts.append(f"Award Letter: {award_letter_and_boq}")
            if remarks:
                remarks_parts.append(remarks)
            full_remarks = "\n".join(remarks_parts)

            # Create or update project
            proj, created = Project.objects.get_or_create(
                project_code=project_code,
                mda=mda,
                defaults={
                    'project_name': project_name,
                    'lot': lot,
                    'project_type': proj_type,
                    'location': location or 'NIGER EAST',
                    'category': category_obj,
                    'budget_amount': budget_amount,
                    'actual_contract_amount': actual_contract_amount,
                    'in_house_benchmark': in_house_benchmark,
                    'cost_percentage': cost_percentage,
                    'mobilization_received': mobilization_received,
                    'batch_no_mobilization': batch_no_mobilization,
                    'batch_no_final_payment': batch_no_final_payment,
                    'final_payment_received': amount_paid,
                    'staff_assigned': staff_obj,
                    'execution_mode': 'SUBCONTRACTED' if (subcontractor_raw or final_companies) else 'SELF_EXECUTED',
                    'current_phase': 'POST_AWARD' if actual_contract_amount > 0 else 'PRE_AWARD',
                    'project_status': 'Awarded' if actual_contract_amount > 0 else 'Initiated',
                    'payment_status': 'Pending',
                    'plain_boq': plain_boq,
                    'drawing_design': drawing_design,
                    'award_letter_and_boq': award_letter_and_boq,
                    'final_companies': final_companies,
                    'back_up_companies': back_up_companies,
                    'technical_status': technical,
                    'financial_status': financials,
                    'remarks': full_remarks
                }
            )

            # Set created_at to 2026 explicitly
            Project.objects.filter(pk=proj.pk).update(created_at=dt_2026)

            # Set Facilitation Fee
            ProjectFee.objects.update_or_create(
                project=proj,
                fee_type=fee_facilitation,
                defaults={'amount': fac_fee}
            )

            # Set Logistics Fee
            if log_fee > 0:
                ProjectFee.objects.update_or_create(
                    project=proj,
                    fee_type=fee_logistics,
                    defaults={'amount': log_fee}
                )

            # Set Subcontractor allocation if specified
            sub_name = subcontractor_raw or final_companies
            if sub_name:
                # Clean name
                sub_clean = sub_name.split('\n')[0].strip()
                if len(sub_clean) > 255:
                    sub_clean = sub_clean[:255]
                if sub_clean:
                    sub_obj, _ = Subcontractor.objects.get_or_create(
                        name=sub_clean,
                        defaults={'company_type': 'EXTERNAL'}
                    )
                    ProjectAllocation.objects.get_or_create(
                        project=proj,
                        subcontractor=sub_obj
                    )

            imported_count += 1

    print(f"Successfully loaded {imported_count} projects for year 2026 into database!", flush=True)

if __name__ == '__main__':
    load_2026_projects()
