# Generated by Django 5.0.6 on 2026-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subcontracting company or internal department.', max_length=255, unique=True)),
                ('company_type', models.CharField(choices=[('INTERNAL', 'Our Company (Internal Team)'), ('EXTERNAL', 'Outside Subcontractor')], default='EXTERNAL', help_text='Is this an internal company or an outside sub-contractor?', max_length=10)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person name.', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subcontractor',
                'verbose_name_plural': 'Subcontractors',
                'ordering': ['name'],
            },
        ),
    ]
