# Generated by Django 5.0.6 on 2026-06-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this document entails.', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this document strictly required for all contractors?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubcontractorCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The calendar year this compliance record belongs to (e.g., 2026)')),
                ('status', models.CharField(choices=[('PENDING', 'Missing / Outstanding'), ('SUBMITTED', 'Submitted / Under Review'), ('APPROVED', 'Approved & Valid'), ('EXPIRED', 'Expired / Needs Renewal')], default='PENDING', max_length=15)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='compliance_docs/%Y/')),
                ('expiry_date', models.DateField(blank=True, help_text='If the document expires mid-year.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_records', to='contractors.compliancerequirement')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='contractors.subcontractor')),
            ],
            options={
                'ordering': ['-year', 'requirement__name'],
                'unique_together': {('subcontractor', 'requirement', 'year')},
            },
        ),
    ]
