# Generated by Django 5.0.6 on 2026-06-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_compliancerequirement_subcontractorcompliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontractor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='email',
        ),
    ]
