# Generated by Django 5.0.6 on 2026-06-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_remove_subcontractor_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255, unique=True)),
                ('contact', models.CharField(help_text='Primary contact person or contact detail', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='company_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='name',
            field=models.CharField(help_text='Name of the subcontractor', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='CompanyCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='The calendar year this compliance record belongs to (e.g., 2026)')),
                ('status', models.CharField(choices=[('PENDING', 'Missing / Outstanding'), ('SUBMITTED', 'Submitted / Under Review'), ('APPROVED', 'Approved & Valid'), ('EXPIRED', 'Expired / Needs Renewal')], default='PENDING', max_length=15)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='compliance_docs/%Y/')),
                ('expiry_date', models.DateField(blank=True, help_text='If the document expires mid-year.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='contractors.company')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontractor_records', to='contractors.compliancerequirement')),
            ],
            options={
                'ordering': ['-year', 'requirement__name'],
                'unique_together': {('company', 'requirement', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='SubcontractorCompliance',
        ),
    ]
