# Generated by Django 5.0.6 on 2026-06-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0004_company_remove_subcontractor_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='directors_name',
            field=models.CharField(default='Azani', help_text='Director name', max_length=255),
            preserve_default=False,
        ),
    ]
