# Generated by Django 5.0.6 on 2026-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0005_remove_company_contact_company_directors_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='directors_name',
            new_name='director_name',
        ),
    ]
