# Generated by Django 5.0.6 on 2026-08-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0006_rename_directors_name_company_director_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='director_name',
            field=models.CharField(blank=True, default='', help_text='Director name', max_length=255),
        ),
    ]
